# Generated by Django 5.1 on 2024-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tododata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
